use ollama_rs::coordinator::Coordinator;
use ollama_rs::{
    generation::chat::{ChatMessage, ChatMessageResponse},
    Ollama,
};
use std::error::Error;
use std::process::Command;
use tauri::Url;

use crate::utils::db;

#[derive(Clone, serde::Serialize, Debug)]
struct ModelData {
    name: String,
    architecture: String,
    context: String,
    capabilities: Vec<String>,
}

/// Read the contents of a file in the repository. Use this to understand what changed.
///
/// * file_path - The relative path to the file from the repository root (e.g. "src/main.rs")
#[ollama_rs::function]
async fn read_repo_file(
    file_path: String,
) -> Result<String, Box<dyn std::error::Error + Sync + Send>> {
    println!("trying to read file: {}", file_path);
    // Safety: only allow relative paths — prevent escaping the repo
    if file_path.contains("..") || file_path.starts_with('/') {
        return Err("Only relative paths within the repository are allowed".into());
    }

    let output = Command::new("git")
        .args(["show", &format!("HEAD:{}", file_path)])
        .output()?;

    if !output.status.success() {
        // Fall back to reading from the working tree
        let content = std::fs::read_to_string(&file_path)
            .map_err(|e| format!("Could not read file '{}': {}", file_path, e))?;
        return Ok(content);
    }

    Ok(String::from_utf8(output.stdout)?)
}

pub(crate) async fn get_all_local_models() -> Result<Vec<String>, Box<dyn Error>> {
    let ollama_server = match db::get_ollama_setting().await?.get("ollama_server") {
        Some(da) => da.clone(),
        None => "".to_string(),
    };
    let ollama = Ollama::from_url(Url::parse(&ollama_server)?);
    let res = ollama.list_local_models().await?;
    let mut local_models: Vec<String> = vec![];
    for local_model in res {
        let model_info = ollama.show_model_info(local_model.name.clone()).await?;
        let architecture = match model_info.model_info.get("general.architecture") {
            Some(architecture) => architecture.to_string().replace("\"", ""),
            None => "".to_string(),
        };
        let context_key = format!("{}.context_length", architecture);

        let context_length = match model_info.model_info.get(&context_key) {
            Some(context) => match context.as_u64() {
                Some(num) => num,
                None => 0,
            },
            None => 0,
        };

        let model_data = ModelData {
            name: local_model.name,
            architecture: architecture,
            context: format!("{}", context_length),
            capabilities: model_info.capabilities,
        };
        local_models.push(serde_json::to_string(&model_data)?);
    }

    Ok(local_models)
}

pub(crate) async fn send_message(
    history: Vec<ChatMessage>,
    request: Vec<ChatMessage>,
) -> Result<ChatMessageResponse, Box<dyn Error>> {
    let ollama_settings = db::get_ollama_setting().await?;
    let ollama_server = ollama_settings
        .get("ollama_server")
        .cloned()
        .unwrap_or_default();
    let ollama_model = ollama_settings.get("model").cloned().unwrap_or_default();

    let ollama = Ollama::from_url(Url::parse(&ollama_server)?);

    let response = Coordinator::new(ollama, ollama_model, history)
        .add_tool(read_repo_file) // generated by #[ollama_rs::function]
        .chat(request)
        .await?;

    Ok(response)
}
